version: '3.3'

services:
  database:
    image: postgres:14
    environment:
     - POSTGRES_DB=blackprop
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=postgres
    ports: 
     - '5432:5432'
    volumes:
     - ./postgres_data:/var/lib/postgresql 
