version: '3.3'

services:
  database:
    image: postgres:14
    # environment:
    #  - POSTGRES_DB=blackprop2
    #  - POSTGRES_USER=admin
    #  - POSTGRES_PASSWORD=postgres
    container_name: local_database
    env_file:
      - ./.envs/.local/.postgres
    ports: 
     - '5432:5432'
    volumes:
     - ./postgres_data:/var/lib/postgresql 

  nest1:
    build:
      context: .
      dockerfile: ./compose/local/nest/Dockerfile
    image: nest_local
    container_name: local_nest
    # command: node dist/main
    command: npm run start:dev
    # entrypoint: ["npm", "run", "start"]
    env_file:
      - ./.envs/.local/.nest
    ports: 
     - '3000:3000'
    volumes:
      - ./:/app
