version: '3.3'

services:
  database:
    # image: postgres:14
    image: postgres:12-alpine
    environment:
     - POSTGRES_DB=climatecoin
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=postgres
    container_name: local_database_climatecoin
    # env_file:
    #   - ./.envdevaws
    ports: 
     - '5432:5432'
    volumes:
     - ./postgres_data:/var/lib/postgresql 

  nest1:
    build:
      context: .
      dockerfile: ./compose/local/nest/Dockerfile
    image: nest_local
    container_name: local_nest
    # command: sh -c "npm run start:dev"
    command: sh -c "sleep 10 && npm run migrations:run && npm run start:dev"
    # command: node dist/main
    # command: npm run start:dev
    # entrypoint: ["npm", "run", "start"]
    env_file:
      # - ./.envs/.local/.nest
      - ./.envlocal
    ports: 
     - '80:3000'
    volumes:
      - ./:/app
    depends_on:
      - database
