name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./compose/local/nest/Dockerfile --tag matamicen/nest_local:latest
    # run: docker build . --file ./compose/local/nest/Dockerfile --tag matamicen/nest_local:$(date +%s)
    
    - name: Docker Push
      run: docker push matamicen/nest_local:latest
    # run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    
    - name: Beanstalk Deploy
  # You may pin to the exact commit or the version.
  # uses: einaregilsson/beanstalk-deploy@6f594ded1b0a22c5e5aa1088e7c58dc5816c92ea
      uses: einaregilsson/beanstalk-deploy@v20
      with:
       aws_access_key: ${{ secrets.AWS_ACCESS }}
       aws_secret_key: ${{ secrets.AWS_SECRET }}
       region: us-east-1
       application_name: nestmat2
       environment_name: Nestmat2-env 
       version_label: nestmat2-source

